# Generated by Django 4.2.2 on 2023-06-15 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0002_product_created_at_product_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='summary',
        ),
    ]
